name: Sugar-CRM-Demo
on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        description: LT Username
      accessKey:
        description: LT Access Key
        required: true
      sampleRepoLink:
        description: Enter the web url
        default: https://lambdatest.com
        required: false
jobs:
  Sugar-CRM-POC:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone ${{ github.event.inputs.sampleRepoLink }}
          echo "STEP 2) Download CLI and setting environment variables"
              git clone https://github.com/ritamganguli/sugar_crm_try.git
              cd sugar_crm_try
              curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
              dir
              export LT_USERNAME=${{ github.event.inputs.username }}
              export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
              ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config url_input.yaml
              echo "Test completed"
